name: GitHub Action CI build

on:
  push:
#    branches-ignore:
#      - dependabot/**
  pull_request:

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [17, 21]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use artifact caching
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -e -B -V -ntp clean package

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
